language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Igh2qHJiRSShavScb+gkf+3VOaDlmV14i1NLcvwBSBIjL8Zb7twRnaLKlKSM2OVKpDbj23/xZz88p7XQkMtDA11TDq66EYMrDFnLBj2gA8El7k0rsO6fhZvVRaXZ5fP6T1F20/CZ7dwPYsmsmChhwtUTgvgm2XLV5/3RxE2EyqsWVq3DjpUvT5Ya5G+msgEoiKGjxAYHWHfG6XDEdMYT79HxLXQAkSfG6E9FXeIbrCzQFTNJuWCkqnMzALDVSP/ZnjBWR5/WDgzSkqe5PlVntTRCy8bnO/Dw8oWxhKRu6oU/xpLtUjOzdENvNSIW82uP+a6J6xt3DabiNjbSwAhqs5y1XJ+ykPSUlnaI5JOH1xDjVwlo9dKiLAE4ZPaxKqZEyORukOE0aBqk2GCnoPwSv2dtgf847B0feHQpToz4neMJdx6GQcAFCN0s/JY5tjU95IapjRjWzSBLTKFFTPwnDQ+eeKfriSl34ifYKvibIAtDOZMxcHViu5inZFUt7CvLzpmOk0uhevIZ2c4BgYUz9GnpVE0ZNvLdibffQoqcW+psdanfR5tQCbLOZnDVHQwul92TfJOE6xLJpjnJ7bym21YLk0c2buBN+NbsRNP56W8fCKsQuqL5Tk+YzLcvosCLxIyuWhG1MjPG09g1/vRQwgGuYlLHh7rqhPkcfWmQCi4=
  app: palette-picker-2018
  on:
    repo: andrew-t-james/palette-picker
notifications:
  email: false
